# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(231, 223)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 231, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.threadcountLayout = QtWidgets.QHBoxLayout()
        self.threadcountLayout.setContentsMargins(0, -1, 0, -1)
        self.threadcountLayout.setSpacing(8)
        self.threadcountLayout.setObjectName("threadcountLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.threadcountLayout.addWidget(self.label)
        self.threadcountLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threadcountLineEdit.sizePolicy().hasHeightForWidth())
        self.threadcountLineEdit.setSizePolicy(sizePolicy)
        self.threadcountLineEdit.setMinimumSize(QtCore.QSize(25, 20))
        self.threadcountLineEdit.setMaximumSize(QtCore.QSize(1, 20))
        self.threadcountLineEdit.setMaxLength(3)
        self.threadcountLineEdit.setObjectName("threadcountLineEdit")
        self.threadcountLayout.addWidget(self.threadcountLineEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.threadcountLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.threadcountLayout)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.printidCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.printidCheckBox.setObjectName("printidCheckBox")
        self.verticalLayout_2.addWidget(self.printidCheckBox)
        self.printtextCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.printtextCheckBox.setObjectName("printtextCheckBox")
        self.verticalLayout_2.addWidget(self.printtextCheckBox)
        self.printoriginCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.printoriginCheckBox.setObjectName("printoriginCheckBox")
        self.verticalLayout_2.addWidget(self.printoriginCheckBox)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.printboardsearchendCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.printboardsearchendCheckBox.setObjectName("printboardsearchendCheckBox")
        self.verticalLayout_2.addWidget(self.printboardsearchendCheckBox)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.threadcountLayout_2 = QtWidgets.QHBoxLayout()
        self.threadcountLayout_2.setContentsMargins(0, -1, 0, -1)
        self.threadcountLayout_2.setSpacing(8)
        self.threadcountLayout_2.setObjectName("threadcountLayout_2")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.threadcountLayout_2.addWidget(self.label_7)
        self.plasterintervalLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plasterintervalLineEdit.sizePolicy().hasHeightForWidth())
        self.plasterintervalLineEdit.setSizePolicy(sizePolicy)
        self.plasterintervalLineEdit.setMinimumSize(QtCore.QSize(40, 20))
        self.plasterintervalLineEdit.setMaximumSize(QtCore.QSize(1, 20))
        self.plasterintervalLineEdit.setMaxLength(6)
        self.plasterintervalLineEdit.setObjectName("plasterintervalLineEdit")
        self.threadcountLayout_2.addWidget(self.plasterintervalLineEdit)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.threadcountLayout_2.addWidget(self.label_8)
        self.verticalLayout_2.addLayout(self.threadcountLayout_2)
        self.printplasterCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.printplasterCheckBox.setObjectName("printplasterCheckBox")
        self.verticalLayout_2.addWidget(self.printplasterCheckBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(55, -1, 55, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.saveButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.saveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("background-color: rgb(200, 200, 200)")
        self.saveButton.setFlat(False)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "[ 전체 ]"))
        self.label.setText(_translate("Form", "HTTP 요청 쓰레드 개수"))
        self.threadcountLineEdit.setText(_translate("Form", "4"))
        self.label_2.setText(_translate("Form", "개"))
        self.label_4.setText(_translate("Form", "[ Delete ]"))
        self.printidCheckBox.setText(_translate("Form", "ID 출력"))
        self.printtextCheckBox.setText(_translate("Form", "제목 출력"))
        self.printoriginCheckBox.setText(_translate("Form", "(댓글) 원본 글 주소 출력"))
        self.label_5.setText(_translate("Form", "[ Search ]"))
        self.printboardsearchendCheckBox.setText(_translate("Form", "게시판 검색 완료 시 출력"))
        self.label_6.setText(_translate("Form", "[ Plaster ]"))
        self.label_7.setText(_translate("Form", "도배 간격"))
        self.plasterintervalLineEdit.setText(_translate("Form", "4"))
        self.label_8.setText(_translate("Form", "초 (4초 이상 권장)"))
        self.printplasterCheckBox.setText(_translate("Form", "각 완료 알림 출력"))
        self.saveButton.setText(_translate("Form", "저장"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

