# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(191, 223)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 170, 191, 25))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(55, 0, 55, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.saveButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("background-color: rgb(200, 200, 200)")
        self.saveButton.setFlat(False)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 189, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.threadcountLayout = QtWidgets.QHBoxLayout()
        self.threadcountLayout.setContentsMargins(5, -1, 0, -1)
        self.threadcountLayout.setSpacing(8)
        self.threadcountLayout.setObjectName("threadcountLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.threadcountLayout.addWidget(self.label)
        self.threadcountLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threadcountLineEdit.sizePolicy().hasHeightForWidth())
        self.threadcountLineEdit.setSizePolicy(sizePolicy)
        self.threadcountLineEdit.setMinimumSize(QtCore.QSize(25, 20))
        self.threadcountLineEdit.setMaximumSize(QtCore.QSize(1, 20))
        self.threadcountLineEdit.setMaxLength(3)
        self.threadcountLineEdit.setObjectName("threadcountLineEdit")
        self.threadcountLayout.addWidget(self.threadcountLineEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.threadcountLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.threadcountLayout)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.printidCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.printidCheckBox.setObjectName("printidCheckBox")
        self.verticalLayout_2.addWidget(self.printidCheckBox)
        self.printtextCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.printtextCheckBox.setObjectName("printtextCheckBox")
        self.verticalLayout_2.addWidget(self.printtextCheckBox)
        self.printoriginCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.printoriginCheckBox.setObjectName("printoriginCheckBox")
        self.verticalLayout_2.addWidget(self.printoriginCheckBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveButton.setText(_translate("Form", "저장"))
        self.label_3.setText(_translate("Form", "[ 전체 ]"))
        self.label.setText(_translate("Form", "HTTP 요청 쓰레드 개수"))
        self.threadcountLineEdit.setText(_translate("Form", "0"))
        self.label_2.setText(_translate("Form", "개"))
        self.label_4.setText(_translate("Form", "[ 글/댓글 삭제 ]"))
        self.printidCheckBox.setText(_translate("Form", "ID 출력"))
        self.printtextCheckBox.setText(_translate("Form", "제목 출력"))
        self.printoriginCheckBox.setText(_translate("Form", "(댓글) 원본 글 출력"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

