# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deletion.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_deleteWidget(object):
    def setupUi(self, deleteWidget):
        deleteWidget.setObjectName("deleteWidget")
        deleteWidget.resize(191, 221)
        self.gridLayoutWidget = QtWidgets.QWidget(deleteWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 191, 202))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.optionLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.optionLayout.setContentsMargins(0, 0, 0, 0)
        self.optionLayout.setHorizontalSpacing(6)
        self.optionLayout.setVerticalSpacing(14)
        self.optionLayout.setObjectName("optionLayout")
        self.mincommentLayout = QtWidgets.QHBoxLayout()
        self.mincommentLayout.setContentsMargins(0, -1, 0, -1)
        self.mincommentLayout.setObjectName("mincommentLayout")
        self.mincommentCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mincommentCheckBox.sizePolicy().hasHeightForWidth())
        self.mincommentCheckBox.setSizePolicy(sizePolicy)
        self.mincommentCheckBox.setText("")
        self.mincommentCheckBox.setObjectName("mincommentCheckBox")
        self.mincommentLayout.addWidget(self.mincommentCheckBox)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.mincommentLayout.addWidget(self.label_3)
        self.mincommentLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mincommentLineEdit.sizePolicy().hasHeightForWidth())
        self.mincommentLineEdit.setSizePolicy(sizePolicy)
        self.mincommentLineEdit.setMinimumSize(QtCore.QSize(25, 20))
        self.mincommentLineEdit.setMaximumSize(QtCore.QSize(1, 20))
        self.mincommentLineEdit.setMaxLength(3)
        self.mincommentLineEdit.setObjectName("mincommentLineEdit")
        self.mincommentLayout.addWidget(self.mincommentLineEdit)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.mincommentLayout.addWidget(self.label_4)
        self.optionLayout.addLayout(self.mincommentLayout, 4, 0, 1, 2)
        self.commentCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("굴림")
        self.commentCheckBox.setFont(font)
        self.commentCheckBox.setObjectName("commentCheckBox")
        self.optionLayout.addWidget(self.commentCheckBox, 2, 0, 1, 1)
        self.minlikeLayout = QtWidgets.QHBoxLayout()
        self.minlikeLayout.setContentsMargins(0, -1, 0, -1)
        self.minlikeLayout.setObjectName("minlikeLayout")
        self.minlikeCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minlikeCheckBox.sizePolicy().hasHeightForWidth())
        self.minlikeCheckBox.setSizePolicy(sizePolicy)
        self.minlikeCheckBox.setText("")
        self.minlikeCheckBox.setObjectName("minlikeCheckBox")
        self.minlikeLayout.addWidget(self.minlikeCheckBox)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.minlikeLayout.addWidget(self.label)
        self.minlikeLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minlikeLineEdit.sizePolicy().hasHeightForWidth())
        self.minlikeLineEdit.setSizePolicy(sizePolicy)
        self.minlikeLineEdit.setMinimumSize(QtCore.QSize(25, 20))
        self.minlikeLineEdit.setMaximumSize(QtCore.QSize(1, 20))
        self.minlikeLineEdit.setMaxLength(3)
        self.minlikeLineEdit.setObjectName("minlikeLineEdit")
        self.minlikeLayout.addWidget(self.minlikeLineEdit)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.minlikeLayout.addWidget(self.label_2)
        self.optionLayout.addLayout(self.minlikeLayout, 3, 0, 1, 2)
        self.exclusionWordButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.exclusionWordButton.setFont(font)
        self.exclusionWordButton.setStyleSheet("background-color: rgb(200, 200, 200)")
        self.exclusionWordButton.setFlat(False)
        self.exclusionWordButton.setObjectName("exclusionWordButton")
        self.optionLayout.addWidget(self.exclusionWordButton, 1, 1, 1, 1)
        self.dateComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateComboBox.sizePolicy().hasHeightForWidth())
        self.dateComboBox.setSizePolicy(sizePolicy)
        self.dateComboBox.setObjectName("dateComboBox")
        self.dateComboBox.addItem("")
        self.dateComboBox.addItem("")
        self.dateComboBox.addItem("")
        self.dateComboBox.addItem("")
        self.dateComboBox.addItem("")
        self.optionLayout.addWidget(self.dateComboBox, 2, 1, 1, 1)
        self.articleCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.articleCheckBox.sizePolicy().hasHeightForWidth())
        self.articleCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("굴림")
        self.articleCheckBox.setFont(font)
        self.articleCheckBox.setObjectName("articleCheckBox")
        self.optionLayout.addWidget(self.articleCheckBox, 1, 0, 1, 1)
        self.writeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.writeLabel.setFont(font)
        self.writeLabel.setText("")
        self.writeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.writeLabel.setObjectName("writeLabel")
        self.optionLayout.addWidget(self.writeLabel, 0, 0, 1, 2)
        self.deletion = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setBold(True)
        font.setWeight(75)
        self.deletion.setFont(font)
        self.deletion.setStyleSheet("background-color: rgb(200, 200, 200)")
        self.deletion.setFlat(False)
        self.deletion.setObjectName("deletion")
        self.optionLayout.addWidget(self.deletion, 5, 0, 1, 1)
        self.cancel = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("background-color: rgb(200, 200, 200)")
        self.cancel.setFlat(False)
        self.cancel.setObjectName("cancel")
        self.optionLayout.addWidget(self.cancel, 5, 1, 1, 1)

        self.retranslateUi(deleteWidget)
        QtCore.QMetaObject.connectSlotsByName(deleteWidget)

    def retranslateUi(self, deleteWidget):
        _translate = QtCore.QCoreApplication.translate
        deleteWidget.setWindowTitle(_translate("deleteWidget", "Form"))
        self.label_3.setText(_translate("deleteWidget", "댓글"))
        self.mincommentLineEdit.setText(_translate("deleteWidget", "0"))
        self.label_4.setText(_translate("deleteWidget", "개 이상은 삭제 X"))
        self.commentCheckBox.setText(_translate("deleteWidget", "댓글 삭제"))
        self.label.setText(_translate("deleteWidget", "공감"))
        self.minlikeLineEdit.setText(_translate("deleteWidget", "0"))
        self.label_2.setText(_translate("deleteWidget", "개 이상은 삭제 X"))
        self.exclusionWordButton.setText(_translate("deleteWidget", "특정 단어 제외"))
        self.dateComboBox.setCurrentText(_translate("deleteWidget", "모두"))
        self.dateComboBox.setItemText(0, _translate("deleteWidget", "모두"))
        self.dateComboBox.setItemText(1, _translate("deleteWidget", "1일 내"))
        self.dateComboBox.setItemText(2, _translate("deleteWidget", "1주일 내"))
        self.dateComboBox.setItemText(3, _translate("deleteWidget", "1달 내"))
        self.dateComboBox.setItemText(4, _translate("deleteWidget", "1년 내"))
        self.articleCheckBox.setText(_translate("deleteWidget", "글 삭제"))
        self.deletion.setText(_translate("deleteWidget", "삭제"))
        self.cancel.setText(_translate("deleteWidget", "중단"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deleteWidget = QtWidgets.QWidget()
    ui = Ui_deleteWidget()
    ui.setupUi(deleteWidget)
    deleteWidget.show()
    sys.exit(app.exec_())

