# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detail.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(758, 447)
        Dialog.setMinimumSize(QtCore.QSize(758, 447))
        Dialog.setMaximumSize(QtCore.QSize(758, 447))
        Dialog.setStyleSheet("background-color: rgb(255, 255, 157);")
        Dialog.setModal(True)
        self.articleTable = QtWidgets.QTableWidget(Dialog)
        self.articleTable.setGeometry(QtCore.QRect(0, 0, 758, 201))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.articleTable.setFont(font)
        self.articleTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.articleTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.articleTable.setObjectName("articleTable")
        self.articleTable.setColumnCount(6)
        self.articleTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.articleTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.articleTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.articleTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.articleTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.articleTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.articleTable.setHorizontalHeaderItem(5, item)
        self.articleTable.horizontalHeader().setDefaultSectionSize(115)
        self.articleTable.horizontalHeader().setMinimumSectionSize(39)
        self.articleTable.verticalHeader().setMinimumSectionSize(23)
        self.commentTable = QtWidgets.QTableWidget(Dialog)
        self.commentTable.setGeometry(QtCore.QRect(0, 200, 758, 221))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.commentTable.setFont(font)
        self.commentTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.commentTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.commentTable.setObjectName("commentTable")
        self.commentTable.setColumnCount(5)
        self.commentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.commentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.commentTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.commentTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.commentTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.commentTable.setHorizontalHeaderItem(4, item)
        self.commentTable.horizontalHeader().setDefaultSectionSize(115)
        self.commentTable.horizontalHeader().setMinimumSectionSize(39)
        self.commentTable.verticalHeader().setMinimumSectionSize(23)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 420, 761, 25))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cancelButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setMinimumSize(QtCore.QSize(55, 0))
        self.cancelButton.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("background-color: rgb(200, 200, 200)")
        self.cancelButton.setFlat(False)
        self.cancelButton.setObjectName("cancelButton")
        self.verticalLayout.addWidget(self.cancelButton, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "detail"))
        item = self.articleTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "제목"))
        item = self.articleTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "댓글"))
        item = self.articleTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "공감"))
        item = self.articleTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "날짜"))
        item = self.articleTable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "게시판"))
        item = self.articleTable.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "링크"))
        item = self.commentTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "내용"))
        item = self.commentTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "원글 제목"))
        item = self.commentTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "날짜"))
        item = self.commentTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "게시판"))
        item = self.commentTable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "링크"))
        self.cancelButton.setText(_translate("Dialog", "나가기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

